# This is a basic workflow to help you get started with Actions

name: Build-sphinx-docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          # By default, checkout uses the GITHUB_TOKEN for authentication
          token: ${{ secrets.MY_API_TOKEN }}

      # Setup Python 3.12 container
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
          
      # Install dependencies for the Python 3.12 container
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          
      # Regenerate new .rst files:
      #  1. delete old .rst files in ./docs (except index.rst)
      #  2. regenenerate new .rst files
      - name: Regenerate docs/*.rst files
        run: |
          sphinx-apidoc -d 8 -f -o docs .
          
      # Build the new htm docs
      - name: Build HTML
        run: |
          cd docs/
          make html
          
      # Push to gh-pages branch using (Python ghp-import)
      - name: Run ghp-import
        run: |
          ghp-import -n -p -f docs/_build/html
